# Site
name: "Lektur"
title: "Lektur"
description: "We write to taste life twice, in the moment and in retrospect.<br>—Anaïs Nin"
logo: "assets/images/avatar.jpg"
favicon: "assets/images/favicon.ico"
baseurl: /blog
google_analytics: ""
locale: "id_ID"
disqus: ""
#mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  aksal:
    name: Aksal
    display_name: Aksal
    avatar: assets/images/avatar.jpg
    email: aksal.sf@gmail.com
    web: https://aksalsf.github.io/blog/
    twitter: 
    description: "Si Empu Repositori"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
